services:
  db:
    image: postgres:latest
    container_name: Postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - '5332:5432'
    volumes:
      - db:/data/postgres
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:
